#:schema node_modules/wrangler/config-schema.json
name = "twikoo"
main = "src/index.js"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2026-06-13"

[[d1_databases]]
binding = "DB" # available in your Worker on env.DB
database_name = "twikoo"
database_id = "2b280831-b57a-4ef9-886c-3a37a89182c7"
